# Generated by Django 5.1.3 on 2024-11-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_adminprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Adminlar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='homevideo',
            options={'verbose_name': 'Orqa fon', 'verbose_name_plural': 'Orqa fon'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
    ]
